package attendance

import (
	"darussunnah-api/internal/features/auth"
	"darussunnah-api/internal/platform/logger"
	"darussunnah-api/internal/platform/whatsapp"
	"darussunnah-api/internal/validators"
	"encoding/json"
	"net/http"
	"time"
)

type Handler struct {
	repo IRepository
}

func NewHandler(repo IRepository) *Handler {
	return &Handler{repo: repo}
}

func (h *Handler) GetToken(w http.ResponseWriter, r *http.Request) {
	startedAt := time.Now()
	userID, ok := currentUserID(r)
	if !ok {
		writeJSONResponse(w, http.StatusUnauthorized, false, "Akses ditolak", nil)
		return
	}
	logger.Info(r.Context(), "attendance token generation started", logger.Field{"operation": "attendance_generate_token", "user_id": userID})

	token, err := h.repo.GenerateToken(userID)
	if err != nil {
		logger.Error(r.Context(), "attendance token generation failed", logger.Field{"operation": "attendance_generate_token", "user_id": userID, "error": err.Error()})
		writeJSONResponse(w, http.StatusInternalServerError, false, "Gagal membuat token QR", nil)
		return
	}

	logger.Info(r.Context(), "attendance token generation completed", logger.Field{
		"operation":   "attendance_generate_token",
		"user_id":     userID,
		"duration_ms": time.Since(startedAt).Milliseconds(),
	})
	writeJSONResponse(w, http.StatusOK, true, "Token berhasil dibuat", map[string]string{
		"token": token,
	})
}

func (h *Handler) Scan(w http.ResponseWriter, r *http.Request) {
	startedAt := time.Now()
	logger.Info(r.Context(), "attendance scan started", logger.Field{"operation": "attendance_scan"})
	var body struct {
		Token string `json:"token"`
	}
	if err := validators.DecodeJSON(w, r, &body); err != nil {
		logger.Warn(r.Context(), "attendance scan rejected invalid payload", logger.Field{"operation": "attendance_scan"})
		writeJSONResponse(w, http.StatusBadRequest, false, "Payload tidak valid", nil)
		return
	}

	if body.Token == "" {
		logger.Warn(r.Context(), "attendance scan rejected empty token", logger.Field{"operation": "attendance_scan"})
		writeJSONResponse(w, http.StatusBadRequest, false, "Token wajib diisi", nil)
		return
	}

	studentID, studentName, err := h.repo.ValidateAndRecordAttendance(body.Token)
	if err != nil {
		logger.Warn(r.Context(), "attendance scan validation failed", logger.Field{"operation": "attendance_scan", "error": err.Error()})
		writeJSONResponse(w, http.StatusBadRequest, false, err.Error(), nil)
		return
	}

	// Async WhatsApp Notification
	go func(sID int, sName string) {
		_, phone, err := h.repo.GetStudentInfo(sID)
		if err != nil || phone == "" {
			return
		}

		msg := "Assalamu'alaikum Wr. Wb.\n\n" +
			"Yth. Wali Santri *" + sName + "*,\n" +
			"Kami informasikan bahwa ananda telah hadir di pondok dan melakukan presensi via QR Code hari ini.\n\n" +
			"Jazakumullahu khairan.\n" +
			"_Admin Darussunnah_"

		if err := whatsapp.SendMessage(phone, msg); err != nil {
			logger.Error(r.Context(), "attendance notification failed", logger.Field{"operation": "attendance_scan_notify", "student_id": sID, "error": err.Error()})
		}
	}(studentID, studentName)

	logger.Info(r.Context(), "attendance scan completed", logger.Field{
		"operation":   "attendance_scan",
		"student_id":  studentID,
		"duration_ms": time.Since(startedAt).Milliseconds(),
	})
	writeJSONResponse(w, http.StatusOK, true, "Presensi berhasil dicatat untuk "+studentName, nil)
}

func currentUserID(r *http.Request) (int, bool) {
	return auth.CurrentUserID(r.Context())
}

func writeJSONResponse(w http.ResponseWriter, status int, success bool, message string, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]interface{}{
		"success": success,
		"message": message,
		"data":    data,
	})
}

// Code generated by ifacemaker; DO NOT EDIT.

// IRepository ...
type IRepository interface {
	// GenerateToken creates a new random token for a student that expires in 5 minutes
	GenerateToken(userID int) (string, error)
	// ValidateAndRecordAttendance checks if the token is valid and records attendance
	ValidateAndRecordAttendance(token string) (int, string, error)
	GetStudentInfo(userID int) (string, string, error)
}
