package settings

import (
	"darussunnah-api/internal/platform/logger"
	"darussunnah-api/internal/validators"
	"encoding/json"
	"net/http"
	"slices"

	"github.com/go-chi/chi/v5"
)

type Handler struct {
	repo IRepository
}

func NewHandler(repo IRepository) *Handler {
	return &Handler{repo: repo}
}

func writeJSONResponse(w http.ResponseWriter, status int, success bool, message string, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]interface{}{
		"success": success,
		"message": message,
		"data":    data,
	})
}

func (h *Handler) GetAll(w http.ResponseWriter, r *http.Request) {
	list, err := h.repo.FindAll()
	if err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		writeJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil)
		return
	}
	writeJSONResponse(w, http.StatusOK, true, "Pengaturan berhasil dimuat", list)
}

func (h *Handler) GetPublic(w http.ResponseWriter, r *http.Request) {
	list, err := h.repo.FindAll()
	if err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		writeJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil)
		return
	}

	allowedKeys := []string{
		"school_name",
		"web_logo_url",
		"web_welcome_text",
		"school_address",
		"school_phone",
		"school_email",
		"school_website",
		"whatsapp_admin_numbers",
		"social_instagram",
		"social_facebook",
		"social_youtube",
		"welcome_speech_name",
		"welcome_speech_role",
		"welcome_speech_image",
		"welcome_speech_text",
		"hero_slides",
		"banner_title",
		"banner_subtitle",
		"banner_image_url",
		"banner_button_text",
		"banner_button_url",
		"psb_payment_bank_name",
		"psb_payment_account_number",
		"psb_payment_account_name",
		"psb_payment_amount",
		"psb_payment_note",
		"psb_payment_instructions",
	}

	publicList := make([]Setting, 0, len(allowedKeys))
	for _, setting := range list {
		if slices.Contains(allowedKeys, setting.Key) {
			publicList = append(publicList, setting)
		}
	}

	writeJSONResponse(w, http.StatusOK, true, "Pengaturan publik berhasil dimuat", publicList)
}

func (h *Handler) Update(w http.ResponseWriter, r *http.Request) {
	key := chi.URLParam(r, "key")
	var req struct {
		Value string `json:"value"`
	}
	if err := validators.DecodeJSON(w, r, &req); err != nil {
		writeJSONResponse(w, http.StatusBadRequest, false, "Invalid request body", nil)
		return
	}

	if err := h.repo.Update(key, req.Value); err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		writeJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil)
		return
	}
	writeJSONResponse(w, http.StatusOK, true, "Setting updated", nil)
}

func (h *Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Get("/", h.GetAll)
	r.Put("/{key}", h.Update)
	return r
}

// Code generated by ifacemaker; DO NOT EDIT.

// IRepository ...
type IRepository interface {
	FindAll() ([]Setting, error)
	Update(key, value string) error
	GetByKey(key string) (string, error)
}
