package teachers

import (
	"darussunnah-api/internal/platform/logger"
	"darussunnah-api/internal/validators"
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
)

type Handler struct {
	repo IRepository
}

func sendJSONResponse(w http.ResponseWriter, status int, success bool, message string, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"success": success,
		"message": message,
		"data":    data,
	})
}

func NewHandler(repo IRepository) *Handler {
	return &Handler{repo: repo}
}

func (h *Handler) GetAll(w http.ResponseWriter, r *http.Request) {
	search := r.URL.Query().Get("search")
	list, err := h.repo.FindAll(search)
	if err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		sendJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil)
		return
	}
	if list == nil {
		list = make([]Teacher, 0)
	}
	sendJSONResponse(w, http.StatusOK, true, "Daftar pengajar berhasil dimuat", list)
}

func (h *Handler) GetByID(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil || id <= 0 {
		sendJSONResponse(w, http.StatusBadRequest, false, "ID pengajar tidak valid", nil)
		return
	}
	t, err := h.repo.FindByID(id)
	if err != nil {
		sendJSONResponse(w, http.StatusNotFound, false, "Pengajar tidak ditemukan", nil)
		return
	}
	sendJSONResponse(w, http.StatusOK, true, "Detail pengajar berhasil dimuat", t)
}

func (h *Handler) Create(w http.ResponseWriter, r *http.Request) {
	var req validators.TeacherRequest
	body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
	if err != nil {
		sendJSONResponse(w, http.StatusBadRequest, false, "Payload permintaan tidak valid", nil)
		return
	}
	if err := validators.DecodeStrictJSON(body, &req); err != nil {
		sendJSONResponse(w, http.StatusBadRequest, false, "Payload permintaan tidak valid", nil)
		return
	}
	if validationErrs := validators.ValidateTeacherRequest(&req); len(validationErrs) > 0 {
		sendJSONResponse(w, http.StatusBadRequest, false, "Validasi gagal", validationErrs)
		return
	}

	t := Teacher{
		Name:     req.Name,
		Subject:  req.Subject,
		Bio:      req.Bio,
		ImageURL: req.ImageURL,
		Email:    req.Email,
		WhatsApp: req.WhatsApp,
	}

	if err := h.repo.Create(&t); err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		sendJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil)
		return
	}
	sendJSONResponse(w, http.StatusCreated, true, "Pengajar berhasil ditambahkan", nil)
}

func (h *Handler) Update(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil || id <= 0 {
		sendJSONResponse(w, http.StatusBadRequest, false, "ID pengajar tidak valid", nil)
		return
	}
	var req validators.TeacherRequest
	body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
	if err != nil {
		sendJSONResponse(w, http.StatusBadRequest, false, "Payload permintaan tidak valid", nil)
		return
	}
	if err := validators.DecodeStrictJSON(body, &req); err != nil {
		sendJSONResponse(w, http.StatusBadRequest, false, "Payload permintaan tidak valid", nil)
		return
	}
	if validationErrs := validators.ValidateTeacherRequest(&req); len(validationErrs) > 0 {
		sendJSONResponse(w, http.StatusBadRequest, false, "Validasi gagal", validationErrs)
		return
	}

	t := Teacher{
		Name:     req.Name,
		Subject:  req.Subject,
		Bio:      req.Bio,
		ImageURL: req.ImageURL,
		Email:    req.Email,
		WhatsApp: req.WhatsApp,
	}

	if err := h.repo.Update(id, &t); err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		sendJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil)
		return
	}
	sendJSONResponse(w, http.StatusOK, true, "Pengajar berhasil diperbarui", nil)
}

func (h *Handler) Delete(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil || id <= 0 {
		sendJSONResponse(w, http.StatusBadRequest, false, "ID pengajar tidak valid", nil)
		return
	}
	if err := h.repo.Delete(id); err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		sendJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil)
		return
	}
	sendJSONResponse(w, http.StatusOK, true, "Pengajar berhasil dihapus", nil)
}

func (h *Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Get("/", h.GetAll)
	r.Get("/{id}", h.GetByID)
	r.Post("/", h.Create)
	r.Put("/{id}", h.Update)
	r.Delete("/{id}", h.Delete)
	return r
}

// Code generated by ifacemaker; DO NOT EDIT.

// IRepository ...
type IRepository interface {
	FindAll(search string) ([]Teacher, error)
	FindByID(id int) (*Teacher, error)
	Create(t *Teacher) error
	Update(id int, t *Teacher) error
	Delete(id int) error
}
