package logs

import (
	"darussunnah-api/internal/platform/logger"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
)

type Handler struct {
	repo IRepository
}

func NewHandler(repo IRepository) *Handler {
	return &Handler{repo: repo}
}

func writeJSONResponse(w http.ResponseWriter, status int, success bool, message string, data interface{}, pagination map[string]interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	payload := map[string]interface{}{
		"success": success,
		"message": message,
		"data":    data,
	}
	if pagination != nil {
		payload["pagination"] = pagination
	}
	_ = json.NewEncoder(w).Encode(payload)
}

func (h *Handler) Routes() chi.Router {
	r := chi.NewRouter()
	r.Get("/", h.GetAll)
	return r
}

func (h *Handler) GetAll(w http.ResponseWriter, r *http.Request) {
	search := r.URL.Query().Get("search")
	limitStr := r.URL.Query().Get("limit")
	offsetStr := r.URL.Query().Get("offset")

	limit, err := strconv.Atoi(limitStr)
	if err != nil || limit <= 0 {
		limit = 50
	}
	if limit > 500 {
		limit = 500
	}

	offset, err := strconv.Atoi(offsetStr)
	if err != nil || offset < 0 {
		offset = 0
	}

	logs, total, err := h.repo.GetAll(limit, offset, search)
	if err != nil {
		logger.Error(r.Context(), "Internal Server Error", logger.Field{"error": err.Error()})
		writeJSONResponse(w, http.StatusInternalServerError, false, "Gagal memproses permintaan (Internal Server Error)", nil, nil)
		return
	}
	writeJSONResponse(w, http.StatusOK, true, "Log aktivitas berhasil dimuat", logs, map[string]interface{}{
		"total":  total,
		"limit":  limit,
		"offset": offset,
	})
}

// Code generated by ifacemaker; DO NOT EDIT.

// IRepository ...
type IRepository interface {
	GetAll(limit, offset int, search string) ([]ActivityLog, int, error)
}
